### PR TITLE
Fix flink sql upsert delete

### LINKED ISSUE #129: Main cdc sync not support delete op
flink cdc to sr, when mysql delete, sr did not delete.

### PR DESCRIPTION
**Pull request by xlfjcg**
Fix #129 

When use flink sql transfer to sr from cdc, and not set sink.properties.columns. the Flink Tableschema columns are not sync to set StreamLoadTableProperties columns in sdk.

### CODE REVIEW

File: starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java [hunk 1]
```diff
@@ -237,20 +237,6 @@ protected StreamLoadResponse send(StreamLoadTableProperties tableProperties, Tab
 
             httpPut.setHeaders(defaultHeaders);
 
-            // TODO move to properties
```
Comment (banmoy) [inline starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java:240]: Will this affects spark connector?

File: src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java [hunk 2]
```diff
@@ -359,6 +369,21 @@ public StreamLoadProperties getProperties() {
 
         if (hasColumnMappingProperty()) {
             defaultTablePropertiesBuilder.columns(streamLoadProps.get("columns"));
+        } else if (getTableSchemaFieldNames() != null) {
```
Comment (banmoy) [inline src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java:372]: Why not add a custom StreamLoadTableProperties for a specific db + table to StreamLoadProperties? I think StreamLoadProperties#tablePropertiesMap is just designed for this case？

**Review by chaoyli — APPROVED** [review]
