### PR TITLE
[BugFix] sql parse error caused by sql function

### LINKED ISSUE #88: 读取StarRocks 表时 谓词下推导致sql解析错误
sql体：
```
insert into sinkTable
select item_key,
       vehicle_id,
      item_type,item_value,modify_time
from HTWSource 
where CHAR_LENGTH(vehicle_id) < 10 ; 
```

任务启动时报错为
``` 
Caused by: java.lang.RuntimeException: Request of get query plan failed with code 500 {"exception":"The Sql is invalid","status":500}
    at com.starrocks.connector.flink.manager.StarRocksQueryPlanVisitor.getQueryPlan(StarRocksQueryPlanVisitor.java:134) ~[?:?]
    at com.starrocks.connector.flink.manager.StarRocksQueryPlanVisitor.getQueryInfo(StarRocksQueryPlanVisitor.java:64) ~[?:?]
    at com.starrocks.connector.flink.table.source.StarRocksSourceCommonFunc.getQueryInfo(StarRocksSourceCommonFunc.java:207) ~[?:?]
    at com.starrocks.connector.flink.table.source.StarRocksDynamicSourceFunction.<init>(StarRocksDynamicSourceFunction.java:83) ~[?:?]
 ```
观察日志发现sql 解析为了
```
21:06:09,066 INFO  com.starrocks.connector.flink.manager.StarRocksQueryPlanVisitor [] - query sql [select * from `bh_vehicle_iot_stream`.`htw_profile_item_info_sr` where (10)]
```

### PR DESCRIPTION
**Pull request by xlfjcg**
fix #88 
let flink to handle function

Signed-off-by: xlfjcg <1937532871@qq.com>

### CODE REVIEW

File: src/main/java/com/starrocks/connector/flink/table/source/StarRocksExpressionExtractor.java [hunk 1]
```diff
@@ -30,59 +24,49 @@
...
+            SUPPORT_FUNC.put(BuiltInFunctionDefinitions.OR, args -> args[0] + " or " + args[1]);
+            SUPPORT_FUNC.put(BuiltInFunctionDefinitions.IS_NULL, args -> args[0] + " is null");
+            SUPPORT_FUNC.put(BuiltInFunctionDefinitions.IS_NOT_NULL, args -> args[0] + " is not null");
+            SUPPORT_FUNC.put(BuiltInFunctionDefinitions.NOT, args -> args[0] + " = false");
         }
 
     @Override
     public String visit(CallExpression call) {
         FunctionDefinition funcDef = call.getFunctionDefinition();
-        if (funcDef.equals(BuiltInFunctionDefinitions.LIKE)) {
```
Comment (hffariel) [inline src/main/java/com/starrocks/connector/flink/table/source/StarRocksExpressionExtractor.java:54]: What's the reason for removing the exceptons?

**Review by hffariel — APPROVED** [review]
